name: Deployment Pipelin

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - name: Instalar dependencias de Node
        run: npm install
      - name: Ejecutar las pruebas
        run: npm run test